---
title: "Calculate Times"
author: "Kalebe da Silva Pinto"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{calculate-times-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# *swistrackr*

O pacote R swistrackr se encontra depositado no Github. Para instalação utilize:


```{package install, message=FALSE}
if(!require(devtools)){
  install.packages('devtools')
}
devtools::install_github("kalebepinto/swistrackr", build_vignettes = TRUE)
```

## Utilização do pacote

### Obter informacoes de dimensao do arquivo background.jpg
```{r setup background}
bg.image <- swistrackr::background(image.jpg = system.file('extdata', 'bg-swistrack-1.jpg', package = 'swistrackr'))
bg.image
```

### Obter informacoes de duracao e framerate do video
```{r setup track_video}
#video.swtr <- swistrackr::track_video(video.avi = system.file('extdata', 'video-swistrack-1.avi', package = 'swistrackr'))
#video.swtr
```


### Definir zonas de interesse no video
```{r setup zones}
#zones.swtr <- zones('image.jpg = bg.image', nzones = 2, pzones = 4)
#zones.swtr
```

### Calcular o tempo em que o objeto permaneceu nas zonas de interesse
```{r setup times}
#times(output.swtr, zones.swtr, video.swtr)
```
